# build for riscv64-qemu
[bin.riscv64-qemu]
target = "riscv64gc-unknown-none-elf"
    [bin.riscv64-qemu.configs]
    board = "qemu"
    driver = "kvirtio,kgoldfish-rtc,ns16550a"
    root_fs = "ext4"

    [bin.riscv64-qemu.env]
    HEAP_SIZE = "0x0180_0000"
    MOUNT_IMG_PATH = "mount.img"

# build for x86_64-qemu
[bin.x86_64-qemu]
target = "x86_64-unknown-none"
    [bin.x86_64-qemu.configs]
    board = "qemu"
    driver = "kvirtio,kgoldfish-rtc,ns16550a"
    root_fs = "ext4"

    [bin.x86_64-qemu.env]
    HEAP_SIZE = "0x0180_0000"
    MOUNT_IMG_PATH = "mount.img"

# build for aarch64-qemu
[bin.aarch64-qemu]
target = "aarch64-unknown-none-softfloat"
    [bin.aarch64-qemu.configs]
    board = "qemu"
    driver = "kvirtio,kgoldfish-rtc,ns16550a"
    root_fs = "fat32"

    [bin.aarch64-qemu.env]
    HEAP_SIZE = "0x0180_0000"
    MOUNT_IMG_PATH = "mount.img"

# build for loongarch64-qemu
[bin.loongarch64-qemu]
target = "loongarch64-unknown-none"
build_std = true
    [bin.loongarch64-qemu.configs]
    board = "qemu"
    driver = "kramdisk"
    root_fs = "ext4"

    [bin.loongarch64-qemu.env]
    HEAP_SIZE = "0x0180_0000"
    CARGO_CFG_DRIVER = "kramdisk"
    MOUNT_IMG_PATH = "mount.img"
