[package]
name = "devfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vfscore = { path = "../../crates/vfscore" }
logging = { path = "../logging" }
devices = { path = "../devices" }
arch = { path = "../../arch" }
log = "0.4.17"
