[package]
name = "frame_allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.1"
log = "0.4"
arch = { git = "https://github.com/Byte-OS/arch.git" }
sync = { path = "../sync" }