[package]
name = "cv1811-sd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-struct = "0.3.2"
log = "0.4"
